### ISSUE TITLE
Which frame for the lin_vel used in the reward function

### ISSUE THREAD

**Issue by meng-zha** [Gepetto/SoloParkour#1]
The paper tells that "where v is the velocity of the base relatively in the robot frame". However, I find that the lin_vel used in ther reward function is from the root_states, which is in the world frame. So which frame should be the correct one?

**Comment by elliotchanesane31** [comment]
Hi, for clarity in the paper, we defined both the base velocity and the velocity command in the robot frame since the velocity command is input to the policy in this frame. However, in the simulation, it's more practical to express the velocity command in the world frame to ensure it always aligns with the direction of the parkour. This is why the lin_vel used in the reward function is also in the world frame. Before feeding the velocity command to the policy, we convert it to the robot frame, as done [here](https://github.com/Gepetto/SoloParkour/blob/44ec132d8faa520ebf1e648f36612efab8e51410/tasks/solo_parkour.py#L587).

**Comment by meng-zha** [comment]
Thank you so much. So the velocity in command is in the robot frame but lin_vel for reward function is in the world frame.
